### ISSUE TITLE
Flask Fails to Run

### ISSUE THREAD

**Issue by gavwellis** [app-generator/flask-boilerplate-dashboard-argon#3]
Hey,

I keep getting the following errors after running 'flask run' after completing all the steps in README.

```
Traceback (most recent call last):
  File "d:\workspace\python\projects\flask-boilerplate-dashboard-argon\env\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\workspace\python\projects\flask-boilerplate-dashboard-argon\run.py", line 29, in <module>
    app = create_app( app_config )
  File "D:\workspace\python\projects\flask-boilerplate-dashboard-argon\app\__init__.py", line 39, in create_app
    register_blueprints(app)
  File "D:\workspace\python\projects\flask-boilerplate-dashboard-argon\app\__init__.py", line 22, in register_blueprints
    module = import_module('app.{}.routes'.format(module_name))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\workspace\python\projects\flask-boilerplate-dashboard-argon\app\base\routes.py", line 17, in <module>
    from app.base.models import User
  File "D:\workspace\python\projects\flask-boilerplate-dashboard-argon\app\base\models.py", line 7, in <module>
    from sqlalchemy import Binary, Column, Integer, String
ImportError: cannot import name 'Binary' from 'sqlalchemy' (d:\workspace\python\projects\flask-boilerplate-dashboard-argon\env\lib\site-packages\sqlalchemy\__init__.py)

```
Any idea why this might be happneing?

Thanks,
Gav

**Comment by app-generator** [comment]
Hello @gavwellis, 

Please provide more information regarding the environment: 

- OS type and version
- Python version
- Execution env (if commands are executed via a simple terminal or from an IDE)

Thank you!

**Comment by gavwellis** [comment]
- Windows 10 Home (Version 2004)
- 3.9.2
- PowerShell

**Comment by app-generator** [comment]
Hello @gavwellis, 

Please update. The app should work as expected.

**Comment by gavwellis** [comment]
Once I manually checked for updates it appeared that many bits were missing. Installed all Windows updates, redeployed the virtual environment and now we are back up and running. Thanks for your help.
